CREATE TABLE [dbo].[CHAR_INFO] (
    [ID]             INT  IDENTITY (1, 1) NOT NULL,
    [Name]           TEXT NOT NULL,
    [Gender]         TEXT NOT NULL,
    [Weight]         TEXT NOT NULL,
    [Height]         TEXT NOT NULL,
    [Race]           TEXT NOT NULL,
    [Class]          TEXT NOT NULL,
    [Skin Color]     TEXT NOT NULL,
    [Hair Length]    TEXT NOT NULL,
    [Hair Style]     TEXT NOT NULL,
    [Hair Color]     TEXT NOT NULL,
    [Eye Color]      TEXT NOT NULL,
    [Upper Clothing] TEXT NOT NULL,
    [Lower Clothing] TEXT NOT NULL,
    [Accessories]    TEXT NOT NULL,
    [Shoes]          TEXT NOT NULL,
    [Bag]            TEXT NOT NULL,
    [Weapon]         TEXT NOT NULL,
    [Companion]      TEXT NOT NULL,
    [Mount]          TEXT NOT NULL,
    [STR]            INT  NOT NULL,
    [AGI]            INT  NOT NULL,
    [INT]            INT  NOT NULL,
    [VIT]            INT  NOT NULL,
    [DEX]            INT  NOT NULL,
    [LUK]            INT  NOT NULL,
    [HP]             INT  NOT NULL,
    [MP]             INT  NOT NULL,
    [Faction]        TEXT NOT NULL
);

